---
- name: get hostname
  command: hostname
  register: hostname

- name: set ssh ciphers
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Ciphers[^\n]*"
    line: Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
    state: present
    backup: yes

- name: set ssh protocol
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Protocol.*$"
    line: Protocol 2
    state: present
    backup: yes

- name: set ssh MACs
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^MACs[^\n]*"
    line: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
    state: present
    backup: yes

- name: "disallow ssh user environment"
  lineinfile:
    create: yes
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitUserEnvironment"
    line: "PermitUserEnvironment no"

- name: "disallow ssh password auth"
  lineinfile:
    create: yes
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: restart sshd
  service: 
    name: sshd 
    state: restarted

- name: install firewalld
  package:
    name: firewalld
    state: present

- name: disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: update packages
  yum:
    name: "*"
    state: latest

- name: disable swap
  shell: swapoff -a

- name: disable swap permanently
  replace:
    path: /etc/fstab
    regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
    replace: '#\1\2\3swap\4'
    backup: yes

- name: modprobe br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: set sysctl variables
  sysctl:
    name: "{{ item }}"
    value: "1"
    sysctl_set: yes
  with_items:
    - net.ipv4.ip_forward
    - net.bridge.bridge-nf-call-iptables

- name: set selinux permissive
  command: setenforce 0

- name: set selinux permissive at boot
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX=enforcing"
    line: SELINUX=permissive
    state: present